SELECT * FROM customer_behavior_table LIMIT 10;

-- Q1 what is the total revenue generated by male vs female customers? 
SELECT 
    gender, 
    SUM(`purchase_amount_(usd)`) AS total_revenue,
    COUNT(*) AS total_customers
FROM 
    customer_behavior_table
GROUP BY 
    gender;
    
    
    -- Q2 which customers used a discount but still spent more than the average purchase amount?
    SELECT 
    customer_id,
    
    `purchase_amount_(usd)`,
    discount_applied
FROM 
    customer_behavior_table
WHERE 
    discount_applied = 'Yes'
    AND `purchase_amount_(usd)` > (
        SELECT AVG(`purchase_amount_(usd)`) 
        FROM customer_behavior_table
    );
    
    
-- Q3 which are the top 5 products with the highest average review rating?
    SELECT 
    item_purchased, 
    ROUND(AVG(review_rating), 2) AS average_rating
FROM 
    customer_behavior_table
GROUP BY 
    item_purchased
ORDER BY 
    average_rating DESC
LIMIT 5;





-- Q4 compare the average purchase amounts between standard and express shipping?
SELECT 
    shipping_type,
    ROUND(AVG(`purchase_amount_(usd)`), 2) AS average_purchase_amount
FROM 
    customer_behavior_table
WHERE 
    shipping_type IN ('Standard', 'Express')
GROUP BY 
    shipping_type;
    
    
 
 
 -- Q5 Do subscribed customers spent more? compare average spent and totatl  reviewnew between subscribers and non subscrivers ?

  SELECT 
    subscription_status,
    COUNT(*) AS total_customers,
    ROUND(AVG(`purchase_amount_(usd)`), 2) AS avg_spend,
    SUM(`purchase_amount_(usd)`) AS total_revenue
FROM 
    customer_behavior_table
GROUP BY 
    subscription_status
ORDER BY 
    subscription_status DESC;
    
    
    -- Q6 which 5 products has the highest percentage of the purchase with discount applied?
SELECT 
    item_purchased,
    COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) AS discount_purchases,
    COUNT(*) AS total_purchases,
    ROUND(
        (COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0) / COUNT(*), 
        2
    ) AS discount_percentage
FROM 
    customer_behavior_table
GROUP BY 
    item_purchased
ORDER BY 
    discount_percentage DESC
LIMIT 5;




-- Q7 segment customers into new, returning and loyal base on their total number of 
-- previous purchase and show the count of each segment?

with customer_type as (
select customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
END AS customer_segment
from customer_behavior_table
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;





-- Q8 what are the top 3 most purchase product within each category ?
  
  

WITH ranked_products AS (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rn
    FROM 
        customer_behavior_table
    GROUP BY 
        category, 
        item_purchased
)
SELECT 
    category,
    item_purchased,
    purchase_count
FROM 
    ranked_products
WHERE 
    rn <= 3;
    
    
    
    
    
      -- Q9 Are customers who are repeat buyers(more than 5 previous purchase ) also like to subscribe?
SELECT 
    subscription_status,
    COUNT(*) AS customer_count,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 2) AS percentage
FROM 
    customer_behavior_table
WHERE 
    previous_purchases > 5
GROUP BY 
    subscription_status;
    
    
    
-- Q10. What is the revenue contribution of each age group?

select age_group,
SUM(`purchase_amount_(usd)`) as total_revenue
from customer_behavior_table
group by age_group
order by total_revenue desc;